.gitlab-ci.yml
setup.py
src/reuse/_util.py
src/reuse/project.py
src/reuse/report.py
tests/conftest.py
tox.ini

Python 3.5 support is difficult to maintain when the project so
extensively uses os.PathLike. Simply dropping it is probably all
right.
If it turns out someone wants Python 3.5 support, just add str
calls _everywhere_.

Remove Python 3.5 support

---

requirements.txt
setup.py
src/reuse/_main.py
src/reuse/_util.py
src/reuse/download.py
tests/test_download.py
tests/test_main.py

A naive implementation that works fairly well.
I still need to extract some functionality from reuse._main.py::download into a separate function, so that a command such as `reuse init` doesn't need to reimplement anything.

Add a method to download licenses

---

README.rst

`git clone git@github.com:fsfe/reuse-tool.git` creates a directory called `reuse-tool/` not `reuse/`

Update directory name in README.rst

---

src/reuse/report.py

Before this change the docstring for files_without_copyright  talks about license information. After this change it refers to copyright as expected.

Amend docstring for files_without_copyright

---

src/reuse/spdx.py

According to article 1.6.4 of [SPDX v2.1.1 Specification](https://spdx.github.io/spdx-spec/1-rationale/) encoding should be UTF-8.
Fixes error in `spdx` command when UTF-8 is not system default encoding (like, Windows):
```
Traceback (most recent call last):
File "c:\root\python\3.6\w64\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "c:\root\python\3.6\w64\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "c:\r\Python\3.6\w64\Scripts\reuse.exe\__main__.py", line 9, in <module>
File "c:\root\python\3.6\w64\lib\site-packages\reuse\_main.py", line 146, in main
return parsed_args.func(parsed_args, out)
File "c:\root\python\3.6\w64\lib\site-packages\reuse\spdx.py", line 35, in run
out.write(report.bill_of_materials())
File …
```

fix: encode SPDX file in UTF-8

---

src/reuse/_util.py

str(Path) uses `\\` separators instead of `/`. Path.as_posix() returns
the path with separators that are expected by debian.copyright.
Reported-by: Basil Peace
Fixes #22

Forward a posix-like path to debian.copyright

---

CHANGELOG.rst
src/reuse/_util.py
src/reuse/download.py
src/reuse/project.py
tests/test_download.py
tests/test_project.py
tests/test_util.py

In the new spec, Valid-License-Identifier and licenses outside of the
LICENSES/ directory are no longer supported. Instead, the file name of
the license must contain the SPDX identifier followed by an extension.
This commit simply removes a lot of functionality and tests that had to
do with this.
See https://github.com/fsfe/reuse-docs/issues/27

Remove Valid-License-Identifier

---

Dockerfile

This PR add a Dockerfile to install reuse in a Docker container based on Alpine. This way, it is easy to integrate in CI processes.
I deliberately did not choose to just install via pip to reduce the dependency on this source, and to be able to build the image and publish it to Docker Hub without the need to have a release on pypi.
Downside to far: The image is quite heavy with 325MB. The install via pip in the same base image results in an image size of ~60MB. I tried `make clean` to get rid of build artifacts, but afterwards the binary didn't run any more. Ideas?

Dockerize tool

---

CHANGELOG.md
src/reuse/download.py
tests/test_main.py

Here's an extremely broken implementation that fixes #45.
The output is currently completely broken (i.e., prints a lot of error messages), but the functionality is there.

Implement `reuse download --all`

---

.pylintrc
CHANGELOG.md
src/reuse/_main.py
src/reuse/_util.py
src/reuse/download.py
src/reuse/header.py
src/reuse/lint.py
src/reuse/project.py
src/reuse/report.py
tests/test_main.py
tests/test_report.py

I discovered today that `reuse addheader` outputs `TODO`, which isn't very nice. I will release a patch for that very soon. To prevent this from happening in the future, I have made pylint check for FIXMEs. If there is a FIXME, the linter will complain. The linter will not complain about TODOs.
The task of this PR is to turn some FIXMEs into TODOs, some TODOs into FIXMEs, and then to actually fix the FIXMEs.

Clear up some TODOs and FIXMEs

---

CHANGELOG.md
src/reuse/_util.py
src/reuse/header.py
tests/test_main.py
tests/test_util.py

This PR kind of works. I spent far too long trying to move this logic down into `_create_new_header`, but that would necessitate writing logic that can find-and-replace year ranges in copyright notices. That's doable, but fairly heuristic-y and makes some heavy assumptions about how people do their year ranges. This will suffice for now, I think.

Automagically add year to header with addheader

---

README.md

I'm actually not sure if that is the most accurate representation since the package manager is actually [Nix](https://nixos.org/nix/) and can be used on every linux distro, macOS and in theory also *BSD and Windows.

Add NixOS package link to README

---

CHANGELOG.md
src/reuse/__main__.py

Allows `python3 -m reuse`, as mentioned in #97

Add __main__ module

---

CHANGELOG.md
src/reuse/lint.py
src/reuse/report.py

This greatly improves the performance of the tool. Instead of reading every single file in full and checksumming them, it simply doesn't do that, and assigns a unique checksum to each file.
Original performance:
```
922.56user 471.02system 25:48.01elapsed 90%CPU (0avgtext+0avgdata 675684maxresident)k
245959016inputs+85696outputs (8major+254525minor)pagefaults 0swaps
```
New performance:
```
480.17user 119.80system 11:18.19elapsed 88%CPU (0avgtext+0avgdata 679352maxresident)k
5052184inputs+85648outputs (0major+243132minor)pagefaults 0swaps
```
Real-time performance is halved.

Do not checksum files when linting

---

AUTHORS.rst
CHANGELOG.md
docs/usage.rst
src/reuse/_util.py
src/reuse/header.py
tests/conftest.py
tests/test_header.py

Fixes #95 
Wrote the code to supercede #95. I ended up reusing a lot of code and ideas by @kirelagin, but went about it a little differently.
This is what the code does:
- Find the first comment block that contains SPDX info.
- Keep the comment block in that place, and preserve everything before and after it.
- Replace the contents of that comment block with new stuff.
- Oversimplified: If a shebang is detected somewhere in there, *deal with it*, and make sure it's at the top of the file.
#95 did much of the same, but made a lot of assumptions along the way. This code makes basically no assumptions at all, other than the following assumption:
- A shebang is any line or multiple of lines that all start with `#!`.
- (Another assumption it implicitly makes is that "the SPDX comment block is …

Preserve shebangs and other pre-SPDX headers

---

CHANGELOG.md
src/reuse/header.py
tests/test_main.py

Fix `addheader --explicit-license` to not break on unsupported files

---

CHANGELOG.md
docs/usage.rst
src/reuse/_main.py
src/reuse/download.py
src/reuse/header.py
src/reuse/init.py
src/reuse/lint.py
src/reuse/report.py
src/reuse/spdx.py
tests/test_main.py

Fixes #94 
Closes #100 
This is an alternative approach to #100 that makes the declaration of the root directory explicit.
It also adds a sanity check: The root of a project must be the parent of all paths that are given to the linter. e.g., if the current working directory is the project root, you can't `reuse lint ../`.
This seems like a sufficient "fix"?

Implement `--root` argument

---

CHANGELOG.md
docs/usage.rst
src/reuse/lint.py
src/reuse/project.py
src/reuse/report.py
tests/test_main.py
tests/test_project.py

Fixes #87
Does the following things:
- If a file `LICENSES/GPL-3.0-or-later` is recognised where `GPL-3.0-or-later` is any valid SPDX License Identifier without file extension, then that license is still recognised.
- The user is given a warning in the above scenario.
- The linter does not pass if any such extensionless licenses are found.
This is an improvement from the simple crash documented in #87.

Deal with extensionless licenses in LICENSES/

---

CHANGELOG.md
docs/usage.rst
src/reuse/_licenses.py
src/reuse/lint.py
src/reuse/report.py
tests/test_lint.py
tests/test_report.py

Fixes #18 
Kind of. It only deals with deprecated licenses, not with the "+" operator.
Together with #89 this is necessary to fix #87 
Not *entirely* happy with this patch, though. The clunkiness of `lint.py` is starting to show. I'm really happy with `report.py` though.
One remark while writing this patch: The order of the items in the `lint` summary is NOT consistent inside of the codebase. It would be nice if this were fixed?

Handle deprecated licenses

---

src/reuse/header.py

Fixes #116
Closes #120
Kind of. This is a workaround that requires a lot less code, but puts the burden on the user to do `--explicit-license`.

When encountering an unsupported filetype, also suggest `--explicit-license` to the user

---

src/reuse/project.py
tests/conftest.py
tests/resources/fake_repository/src/custom.py

Fixes #128 
Really simple fix. Tests have been updated to make sure this does not happen again.

Make sure that Project.license_map only contains dictionaries

---

CHANGELOG.md
src/reuse/_main.py
src/reuse/lint.py
src/reuse/report.py
src/reuse/spdx.py
tests/conftest.py
tests/test_main.py
tests/test_report.py

Okay so this is a fun one. Ignore all the errors: That's all normal. I turned on multiprocessing for the linting process. Just to see if it could be done, and just to see if it has any perceivable speed increase.
... And it does have a speed increase! I haven't done any professional, thorough, scientific measuring, but here's the result from one run each:
|           Multiprocessing            | Time (mm:ss) |
| :----------------------------------: | :----------: |
| Linux kernel without multiprocessing |     1:15     |
|  Linux kernel with multiprocessing   |     0:39     |
| reuse-tool without multiprocessing | 0:01.01 |
| reuse-tool with multiprocessing | 0:01.13 |
| CPython without multiprocessing | 0:06.00 |
| CPython with multiprocessing | 0:03.19 |
Running on an eight-core Ryzen …

Add multiprocessing

---

CHANGELOG.md
src/reuse/_comment.py

Fixes #136 
Casually went through this list: https://github.com/pygments/pygments/blob/master/pygments/lexers/_mapping.py
and started adding comment styles. This is not nearly all-encompassing, but I'm trying to write a licence compliance tool, not a lexer :x Ah well.

More comment styles

---

CHANGELOG.md
docs/conf.py
src/reuse/_comment.py
src/reuse/header.py
tests/test_main.py

* src/reuse/_comment.py(FILENAME_COMMENT_STYLE_MAP):
map from well-known full filenames to comment style
* src/reuse/header.py(_get_comment_style): introduce new helper
function that tries to detect file comment style by consulting
both COMMENT_STYLE_MAP and FILENAME_COMMENT_STYLE_MAP.
* src/reuse/header.py: replace call sites of COMMENT_STYLE_MAP with
calls to `_get_comment_style`.
This change enables automatic detection of comment style for files that
have well-known names with extension, like "manifest" -- shell script,
used by "cdist" configuration management system. Previously, such files
required comment style to be specified explicitly by `--style` command
line option.
Fixes #135

Recognize comment style by well-known filenames

---

src/reuse/_util.py
tests/test_util.py

The SPDX Specification does not specify that the whitespace between the `SPDX-License-Identifier:` string and the license expression must be a single space. The regular expression already matched multiple spaces or space-and-tab combinations before, so allowing a tab directly after the `SPDX-License-Identifier:` string improves consistency.

allow tab after SPDX-License-Identifier

---

CHANGELOG.md
src/reuse/header.py
tests/test_header.py
tests/test_main.py

addheader: No longer remove newlines at the ends of files

---

CHANGELOG.md
src/reuse/header.py
tests/test_header.py
tests/test_main.py

Fixes #153 
I was really unhappy with the solution I wrote in #164. I reverted that PR and wrote this instead, which is heaps and heaps and heaps more elegant.

Preserve newlines at the ends of files with addheader - alternative implementation

---

docs/usage.rst
src/reuse/_comment.py

Though #173 is not resolved by this, it did mention a comment style I had not seen before. So it's added here.

Support JSX comment style

---

.github/workflows/pythonpackage.yml

This PR adds a step in the CI to test whether the Dockerfile can be built and whether the result successfully lints the source of this programme.
Thereby, we should be able to detect whether changes in some base image will result in errors.
Fixes #171

Tests for Dockerfile and Docker image

---

src/reuse/_comment.py

This pull request adds file-extension recognition for 2 types of files used by the [Isabelle theorem prover](http://isabelle.in.tum.de), and one filename match for the same, mapping all three to the existing ml-comment style.
All three are recognised by syntax highlighting/linguist on github and satisfy their uniqueness requirements, so should be safe to add.
(We're in the process of converting a few larger repositories such as https://github.com/sel4/l4v to SPDX tags, and `reuse addheader` recognising these file types would be really handy).

add file extensions for Isabelle prover

---

src/reuse/_comment.py

CMake uses # for comments (`PythonCommentStyle`), and it's already in the extension map as *.cmake -> `PythonCommentStyle`, but `CMakeLists.txt` was missing from the filename mapping.

Add CMakeLists.txt to filename comment style map

---

CHANGELOG.md
src/reuse/_util.py

Fixes #195. Windows appears to dislike pathlib arguments to subprocess.
This didn't need to be in #197 after all.

Cast subprocess arguments to strings

---

tox.ini

This was previously missing and caused Tox to fail. Because Tox isn't used by CI, I never noticed this.

Add requirements-dev.txt to all Tox jobs

---

CHANGELOG.md
src/reuse/project.py
tests/test_project.py

This fixes a rare bug where a directory is ignored and contains a .git file.
Fixes #203

Change an *if* into an *elif*

---

.pre-commit-config.yaml

Inspired by #212, this commit adds pylint to the repo's pre-commit hooks.

Add pylint to pre-commit

---

AUTHORS.rst
CHANGELOG.md
Dockerfile
README.md
docs/usage.rst
src/reuse/__init__.py
src/reuse/_util.py
src/reuse/init.py
src/reuse/project.py
src/reuse/report.py
src/reuse/vcs.py
tests/conftest.py
tests/test_project.py
tests/test_util.py
tests/test_vcs.py

Fixes #99 as far as running the tool on a couple of repos of my own went.
I won't claim that this is comprehensive support for Mercurial as compared to the current git support but it got the tool working for me and generating sensible reports (vs checking my build artifacts). I did try to add some tests as far as code paths that seemed relevant to running `hg` versus `git` goes.
I could probably add a few more tests if needed but I am not sure what you would think are tests that really need a specific check when run using mercurial versus git.

Add basic mercurial support

---

AUTHORS.rst
CHANGELOG.md
requirements.txt
src/reuse/_licenses.py
src/reuse/_util.py
src/reuse/download.py
src/reuse/init.py
tests/test_util.py

Suggest corrections for typos like "GLP3-or-lter" and unclear licenses like "BSD" in init and download commands.

Suggest valid SPDX License Identifiers when invalid one is given

---

CHANGELOG.md
Dockerfile
README.md

This PR is tangent to https://github.com/fsfe/reuse-action/pull/4 and https://github.com/fsfe/reuse-action/pull/3.
In summary, instead of doing this:
```
docker run --volume $(pwd):/data fsfe/reuse reuse lint
```
You do this:
```
docker run --volume $(pwd):/data fsfe/reuse lint
```
This requires an update to https://reuse.software/dev/

Improved Docker entrypoint

---

AUTHORS.rst
docs/usage.rst

In the [`usage/addheaer` docs](https://reuse.readthedocs.io/en/stable/usage.html#addheader) the same arguments was listed twice as 'can be used multiple times'.
Tested with --license, worged so i assume it was meant to be the --license flag.

Fix typo in docs

---

README.md

This was sorely lacking previously.

Add example of header to README

---

CHANGELOG.md
src/reuse/__init__.py
tests/test_project.py

These licenses contain SPDX tags referring to themselves. This causes issues in #229. Ignoring them is a workaround.

Ignore CAL-1.0 and CAL-1.0-Combined-Work-Exception

---

CHANGELOG.md
src/reuse/header.py

This addresses #221 — Python already takes care of decoding arguments correctly, but the default mode of the files depends on `locale.getpreferredencoding(False)` (see https://docs.python.org/3/library/functions.html#open).
Since most languages are now enforcing utf-8 encoding for source code, this should be a positive change for all of them.

Always explicitly encode output files in UTF-8

---

.github/workflows/latesttag.py
CHANGELOG.md
docs/usage.rst
src/reuse/header.py
src/reuse/project.py
tests/conftest.py
tests/test_lint.py
tests/test_main.py
tests/test_main_addheader.py
tests/test_project.py
tests/test_report.py

Fixes #202 
Fixes #208 
This patch ignores *all* symlinks, not just relative ones.

Ignore symlinks and 0-sized files

---

src/reuse/_comment.py

File suffixes `.mk` are used for Makefile, recognize those files.
Signed-off-by: Paul Spooren <mail@aparcar.org>

_comment: recognize Makefile .mk suffix

---

src/reuse/_comment.py

The comment syntax is documented at https://mesonbuild.com/Syntax.html#comments and matches Python's.

Add Meson's meson.build to the supported files.

---

src/reuse/header.py

Since the file will be written out in UTF-8, it's a safe bet that they should also be read in UTF-8.
Alternatively, we could support a global setting to override the default encoding, but in 2020 that sounds like a recipe for more headaches than not.

Use UTF-8 explicitly when reading files, too.

---

src/reuse/_comment.py

This adds entries to `EXTENSION_COMMENT_STYLE_MAP` for Scheme (.scm) and ClojureScript (.cljs, .cljc) files using `LispCommentStyle`.

Detect comment style for Scheme (.scm) and ClojureScript (.cljs, .cljc) files

---

src/reuse/_comment.py

As https://github.com/fsfe/reuse-tool/pull/234/ seems to have stalled for legal reasons, I am submitting a new PR containing just the change of adding support for `go.mod` files.
A `go.mod` file is a Go module definition, similar to a Makefile.

Add go.mod support

---

src/reuse/_comment.py

Add support for windows batch files and fortran
There is a pre-commit hook that runs black coding style checker. It fixed can_handle_single & can_handle_multi. I can undo these changes, but then I have to disable the pre-commit hook provided by the repo.

add windows bat and fortran, fix black coding style issue

---

docs/usage.rst
src/reuse/_util.py
src/reuse/header.py
tests/test_util.py

adds the arg `--copyright-style` which accepts `spdx`, `string` and
`symbol`.
I don't this this option is relevant to the `init` function.
Signed-off-by: Paul Spooren <mail@aparcar.org>

allow different styles of copyright lines

---

src/reuse/_comment.py

RMarkdown[1] is simply Markdown with embedded R code.
Therefore comments are HTML-style, like in Markdown.
[1]: https://rmarkdown.rstudio.com/

Add R Markdown (.Rmd) file extension

---

src/reuse/_comment.py

The extensions .plantuml, .puml, .iuml, and .pu are all associated with
PlantUML, according to fileinfo.com, file-extension.org, and
fileinfo.co.
The simple .uml extension is used by several other UML applications and
thus shouldn’t be hard-coded to PlantUML.
Fixes GitHub issue gh-271

Add PlantUML comment style

---

src/reuse/_comment.py

.tsx is just a naming convention for TypeScript JSX files.

Use JsxCommentStyle for TSX files

---

src/reuse/_comment.py

TypeScript (.ts) files use the same comment style as Javascript files (.js)

Use CCommentStyle for TS files

---

src/reuse/_comment.py

I just made a Ruby on Rails project REUSE compliant and noticed the `Gemfile` and `Rakefile` were not covered yet.
I also like to keep my Docker container build contexts small so added `.dockerignore` as well.

Make addheader detect .dockerignore, Gemfile and Rakefile

---

src/reuse/_comment.py

Support the syntax for the default Jenkins pipeline filename 'Jenkinsfile'. The
syntax is Groovy, so CCommentStyle is used (`//` and `/* ... */`). Have tested
this and it works.

feat: Support Jenkinsfile for comment style

---

src/reuse/_comment.py

.coveragerc files are common for configuring the coverage.py behavior, also used
by pytest. More details on the syntax are available in the coverage.py
documentation: https://coverage.readthedocs.io/en/latest/config.html

feat: support comments in .coveragerc files

---

src/reuse/_comment.py

To distinguish JavaScript modules from non-module files, some sources recommend using the `.mjs` extension [1]. They are otherwise identical to JavaScript `.js` files.
[1]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules#aside_—_.mjs_versus_.js

Add support for .mjs files

---

src/reuse/_comment.py
src/reuse/header.py
tests/test_main_addheader.py

Previously, only binary files were handled as uncommentable [0]. For
other files the "--explicit-license" flag has to be set explicitly.
However, there are also text files which are uncommentable.
This commit / pull request introduces support for a new pseudo comment
style for uncommentable text files.
One use case is, for example, Golang's go.sum file. Hashes of the
referenced modules are listed there, but without any special header [1].
Thus it is not possible to add an SPDX header. However, this file cannot
be omitted. Whether the file is to be ignored license-wise was addressed
in a previous pull request [2], but not clarified.
With the changes introduced here, this file is recognized as
uncommentable and a .license file is created.
[0] …

Comment style for uncommentable files

---

src/reuse/_comment.py

Although there have been discussions on notebooks to support metadata, license
information is not included in those discussions:
https://github.com/ipython/ipython/issues/6073
https://github.com/jupyter/nbformat/blob/master/nbformat/v4/nbformat.v4.schema.json
Also it would be complicated to add license information in the JSON structure if
it were supported.
So for now it is best to consider it uncommentable and add a .ipynb.license file.

feat: .ipynb UncommentableCommentStyle support

---

src/reuse/__init__.py

In order to solve issue https://github.com/fsfe/reuse-tool/issues/227
.hgtags is not a file that is managed by humans, so it makes sense to ignore it.

Ignore .hgtags file

---

src/reuse/_comment.py

Although SVG files can be considered plain-text, they are not suitable for
including copyright and license information.
This commit renders them 'uncommentable' so a .license file is added.

feat: support uncommentable style for .svg files

---

src/reuse/_comment.py

CSV files cannot be annotated as their structure ensure the correct
interpretation of the enclosed data. I'm not aware of csv extensions for
comments, and in any case they wouldn't be supported by all tools.
This commit renders them 'uncommentable' to ensure that a .license file is added.

feat: support uncommentable style for .csv files

---

src/reuse/_comment.py

The sonar-project.properties file is to configure SonarScanner on a repository
level. More documentation can be found at:
https://docs.sonarqube.org/latest/analysis/scan/sonarscanner/
This commit ensures this file format is supported for the addheader command.

feat: support commentable style for sonar-project.properties files

---

src/reuse/_comment.py

This commit ensures that the .bashrc filename is supported for the addheader
command.
The .bashrc files are used to configure the bash terminal. Typically they are
included from other bash configuration files. It is similar to a bash
script like the already supported .bash extension. In this case however the
hashbang will typically not be there.

feat: support comment style for .bashrc files

---

src/reuse/_comment.py

Correct the supported filename for Python source package configurations from
Manifest.in to the expected MANIFEST.in. Manifest.in is the default location for
this location, as is described in the Python packaging documentation:
https://packaging.python.org/guides/using-manifest-in/
This commit was preceded by a small consideration as documented in issue
https://github.com/fsfe/reuse-tool/issues/306

fix: comment support from Manifest.in to MANIFEST.in

---

AUTHORS.rst
CHANGELOG.md
src/reuse/_comment.py

Use  `LispCommentStyle` for Racket, and `PythonCommentStyle` for Org files.

Add comment styles for Racket and Org files

---

CHANGELOG.md
src/reuse/report.py
tests/test_report.py

For some reason, unused licenses were not at all detected. This commit
fixes that, and adds a test.
Fixes #285

Fix unused_licenses regression

---

AUTHORS.rst
CHANGELOG.md
src/reuse/_util.py
src/reuse/header.py
tests/test_util.py

Previously it was only checked that the given file is writable.  For example, non-existing files are writable so an exception was raised after validation when trying to open the file. To fix this, introduce "r+" mode to `PathType` which validates that the file is both readable and writable.

Validate file is readable in addheader subcommand

---

CHANGELOG.md
src/reuse/_util.py
src/reuse/header.py
tests/test_main_addheader.py
tests/test_util.py

Fixes #308 
The implementation is rather naive. Approximately:
1. Check whether `\r\n`, `\r`, or `\n` occurs at all in a file, in that order.
2. If yes to any of the above, assume that that's the line ending for the entire file.
3. Convert the string buffer to `\n` line endings for normal use inside of Python.
4. Do REUSE stuff.
5. Convert the string buffer back to the detected line endings when writing to a file.
It works, though.

Preserve line endings

---

CHANGELOG.md
setup.py

Fixes #311 
*Technically* we could exclude 0.1.39 only from Windows installs. It works just fine on Linux. That would mess with wheel installs, though.

Adjust versioned dependency on python-debian

---

src/reuse/_comment.py

devicetree files (.dts, and .dtsi) use a C comment style.
Add support for them.
Link: https://www.devicetree.org/
Signed-off-by: Liam Beguin <liambeguin@gmail.com>

comment: add comment style for devicetree files

---

docs/usage.rst
src/reuse/_util.py
tests/test_util.py

The REUSE FAQ page [here](https://reuse.software/faq/#copyright-symbol) includes the copyright symbol along with the spdx key as a recommended copyright style, giving the following example:
```
SPDX-FileCopyrightText: © 2019 John Doe <joe@example.com>
```
The `addheader` subcommand's `--copyright-style` option takes `spdx` and `symbol` as options which will provide either the spdx key or the copyright symbol respectively, but doesn't have an option for using both together. This adds `spdx-symbol` as an option to do this.
Fixed #329

add spdx-symbol copyright style

---

src/reuse/_comment.py

Improve the Gradle support by adding some more comment files for
`gradle-wrapper.properties` and `gradlew` as suggested in
https://github.com/fsfe/reuse-tool/issues/351

feat: better Gradle files support

---

src/reuse/project.py

Hi,
I noticed a little error in one of the calls to format, in `spdx_info_of`.
With the current code, if that call gets executed it will result in a `KeyError` exception.

Fix format call in sdpx_info_of

---

README.md

Improve example so multiples executions don't generate a lot of containers that have no use anymore.
Great application by the way.

Add --rm to docker examples

---

.github/workflows/pythonpackage.yaml
CHANGELOG.md
Dockerfile-debian
Dockerfile-extra
README.md

This makes the tag `latest-extra` build like the normal file with the extra packages, and not use `fsfe/reuse:latest` as base.
Additionally, it creates a new Dockerfile using `python:slim-buster` as base. It's ~200% larger but should be easier to comply with as alpine has its issues in this regard.

Improve extra Docker image, add a Debian-based

---

src/reuse/_comment.py

This solves #366 .
([previous/deprecated PR](https://github.com/fsfe/reuse-tool/pull/370))

Support Markdown-linter config file

---

src/reuse/header.py

The special first-line in XML file needs to remain first line, else, the file becomes invalid regarding in the XML spec, and most editors will not recognize the file.
This PR uses the same technique used for shebangs, to protect the first lien in XML files.
This solves #230 (barely).

Do not break XML files special first line

---

setup.py

`reuse/__init__.py` imports pkg_resources

Explicitly require setuptools

---

CHANGELOG.md
src/reuse/_comment.py

https://docs.asciidoctor.org/asciidoc/latest/comments/
I'm afraid the C comment style only matches partially (multi line is different) but I'm not sure when multi line is chosen. I can also adapt to add a new style.
I chose the extensions that are listed here: https://asciidoctor.org/docs/asciidoc-recommended-practices/#document-extension

Add support for AsciiDoc

---

CHANGELOG.md
src/reuse/_comment.py

Fixes #388 
Test file (`test.hbs`):
```
{{#with person}}
{{firstname}} {{lastname}}
{{/with}}
```
Command: `reuse addheader --license "GPL-3.0-or-later" --copyright "Free Software Foundation Europe <https://fsfe.org>" test.hbs`
Result:
```
{{!--
SPDX-FileCopyrightText: 2021 Free Software Foundation Europe <https://fsfe.org>
SPDX-License-Identifier: GPL-3.0-or-later
--}}
{{#with person}}
{{firstname}} {{lastname}}
{{/with}}
```
@ghost91-, could you please confirm that this is correct?

Add handlebars comment and file support

---

README.md

The reuse package has been moved to the community repository from the AUR. 👍

docs: update package reference for Arch Linux

---

CHANGELOG.md
src/reuse/_comment.py

Vue.js single file components are using the HTML comment style, [see Vue.js doc](https://v3.vuejs.org/guide/single-file-component.html#what-about-separation-of-concerns)
closes #395

Vue.js single file component header support

---

CHANGELOG.md
src/reuse/header.py
tests/test_main_addheader.py

Fixes #346 
But relaxes a check on all path arguments passed to addheader command.
There are no tests for graceful permission handling yet.
So this is WIP. Just wanted to let people know someone picked up the issue.

Allow creating .license file for write-protected files

---

README.md

Section 4.8.4.4 of the HTML Standard requires most img elements to have an alt
attribute that isn't empty[1]. Subsections of 4.8.4.4 offer instructions for
what to do in specific scenarios. None of the scenarios exactly match the
shields. Subsection 4.8.4.4.3 seems like the closest match[2], but we don't
know exactly what the shields will say. Subsection 4.8.4.4.2 is also
relevant[3].
1. https://html.spec.whatwg.org/multipage/images.html#alt
2. https://html.spec.whatwg.org/multipage/images.html#a-phrase-or-paragraph-with-an-alternative-graphical-representation:-charts,-diagrams,-graphs,-maps,-illustrations
3. https://html.spec.whatwg.org/multipage/images.html#a-link-or-button-containing-nothing-but-the-image

Add alt text for README's shields

---

CHANGELOG.md
README.md
src/reuse/_main.py
src/reuse/supported_licenses.py
tests/test_main.py

Starting simple:
- new `supported-licenses` command
- prints all supported licences with id, name and reference
- each one in a single line
- the fields are tab separate
closes #363

Add "supported-licenses" command

---

CHANGELOG.md
src/reuse/_util.py
tests/test_util.py

Related to #364. Entering invalid identifiers like `CC0` and `GPL` will now suggest valid identifiers which start with the inputted string while typos are still detected as before.

Suggest valid SPDX identifiers based on prefix

---

CHANGELOG.md
src/reuse/header.py
tests/test_main_addheader.py

Fix regression for files without permissions.

---

CHANGELOG.md
src/reuse/_comment.py

The podman tool supports now both Containerfile and Dockerfile. This is
another name for the same file format.
Fixes #447.

Support Containerfile

---

CHANGELOG.md
src/reuse/_comment.py

We added support for meson.build file in #251 but we need also to
support meson_options.txt[1], used to add build options.
[1] https://mesonbuild.com/Build-options.html
Fixes #445.

Add support for meson_options.txt

---

CHANGELOG.md
setup.py

distutils is going away soon, and the reuse tool's `setup.py` depends on it for the `cmd.Command` class. Fortunately, setuptools vendors `distutils.cmd.Command` as `setuptools.Command`, and has for a long time. (I checked as far back as setuptools 49; it was already there.)
Fixes #450

Don't depend on distutils

---

CHANGELOG.md
README.md

Managing python, pip and virtual environments can be too much work sometimes especially for a project that is not itself written in python. pipx is a convenient shortcut, but people unfamiliar with the python ecosystem might not even know it exists. To mitigate this I have added an example of running your tool via pipx to your readme.

Recommend installation via pipx

---

AUTHORS.rst
tests/conftest.py
tests/resources/fake_repository/.reuse/dep5
tests/resources/fake_repository/src/source_code.c
tests/resources/fake_repository/src/source_code.html
tests/resources/fake_repository/src/source_code.jinja2
tests/resources/fake_repository/src/source_code.py
tests/test_header.py
tests/test_main_addheader.py
tests/test_project.py
tests/test_report.py
tests/test_util.py

I replaced all occurrences of Mary Sue to Jane Doe in all test files, I also found Mary Sue in the header of some source files,
but I replaced them due to you mentioning that you wanted to replace the name in all code base.
fixes #460

Rename Mary Sue to Jane Doe

---

.github/workflows/docker.yaml
.github/workflows/latesttag.yaml
.github/workflows/pythonpackage.yaml

- Move Docker out of pythonpackage
- Better describe latesttag
- Make docker workflow also push the Docker images to Dockerhub (as they made autobuild cost money)
- Publish docker images as amd64 and arm64. Fixes #449

Tidy up workflows and extend by multi-platform Docker image push

---

CHANGELOG.md
src/reuse/header.py
tests/test_main_addheader.py

Rename --explicit-license to --force-dot-license and improve its help text

---

.prettierignore

Some people have a `/venv` which makes `make prettier` go though all files there.
You could theoretically also make prettier just be based on `.gitignore`, but that would then not ignore the SPDX files.
So given this, the while .prettierignore file probably has to be extended to catch locally ignored files, e.g. .Python, dist, lib, .cache or whatever, that are currently caught by .gitignore.
@carmenbianca What do you think?

Extend .prettierignore

---

CHANGELOG.md
src/reuse/_comment.py
src/reuse/header.py
tests/test_comment.py
tests/test_main_addheader.py

Will fix #187 once I've worked out all the details. I began by doing some refactoring in `_comment` to stop stripping all the text. I'll continue by removing the stripping from `header`, and then finally we'll get somewhere hopefully.

Make sure there's a newline at the end of .license files

---

CHANGELOG.md
src/reuse/report.py
tests/test_report.py

Fixes #123 
Fixes #275 
Example: if `Apache-1.0+` appears as a declared license, it should not be identified as missing, bad, or unused if `LICENSES/Apache-1.0.txt` exists. It is, however, identified separately as a used license.
This does **not** fix all of #123. `GPL-3.0+` and `GPL-3.0-or-later` are (still) recognised as separate licenses. I guess this is kind of in line with how SPDX treats GPL anyway. Do we want to fix this?
Furthermore, this patch allows for weird stuff like `GPL-3.0-or-later+`. I guess we can just ignore that weirdness.

Better support for unary "+" operator in license identifiers

---

.github/workflows/license_list_up_to_date.py
.github/workflows/license_list_up_to_date.yaml
Makefile

Fixes #490
I use a different Github API than @carmenbianca introduced in #489 that directly outputs the latest stable release (no draft or pre-release) and shows the connected tag.
~~Also bumps the SPDX license list data to 3.16, released today.~~

Make update-resources pull from latest stable release

---

CHANGELOG.md
src/reuse/resources/exceptions.json
src/reuse/resources/licenses.json

3.17 has been released today.
I used the new routine in the Makefile to update the resources to test it in practice.

Update SPDX licenses/exceptions lists to 3.17

---

AUTHORS.rst
docs/index.rst
docs/scripts.rst

Add a section in the documentation with scripts to help with getting the information for the addheader command.
Provides some examples related to #297 and #349.
More work is necessary to suggest copyright on a per-file basis and to provide author details for reuse users wanting to add headers for their own contributions.
To be explicit about the dual-licensed copyright the SPDX snippet headers are added. These are not yet supported by SPDX but are intended for SPDX 3.0 https://github.com/spdx/spdx-spec/pull/464 If the SPDX specification turns out differently, these headers can be modified appropriately.
Signed-off-by: Nico Rikken <nico.rikken@fsfe.org>

Add script in documentation for requested use-cases

---

CHANGELOG.md
src/reuse/__init__.py
src/reuse/spdx.py

Fixes #442
The regexes could also be combined to `.*\.spdx(.(rdf|json|xml|ya?ml))?$` but I figured that this may rather increase confusion. One could also simplify `ya?ml` to `yaml|yml` but I think that's still an easy one.

Ignore more SPDX file formats

---

CHANGELOG.md
src/reuse/__init__.py
src/reuse/_main.py
src/reuse/project.py
tests/test_main.py

Meson subprojects should be handled similarly to git submodules. Meson
subprojects may actually be git submodules, but they may also just be
regular directories e.g. included via git subtree or via other means.
If the project of question uses meson as its build system, e.g. has the
following file:
./meson.build
Then directories in the subprojects root directory should be ignored by
default:
./subprojects/libfoo/foo.c
./subprojects/libbar/bar.c
Normal files in the subprojects root directory are normally parsed:
./subprojects/libfoo.wrap
./subprojects/libbar.wrap
This can be overriden with the command line switch:
reuse --include-meson-subprojects lint
Relevant resources are at [1] and [2].
[1] https://mesonbuild.com/Subprojects.html
[2] …

ignore meson subproject directories

---

CHANGELOG.md
src/reuse/_comment.py

Recognise .kts files as Kotlin script, using the C comment style.
Closes #519

Kotlin script support

---

src/reuse/_util.py
tests/conftest.py
tests/test_header.py
tests/test_lint.py
tests/test_main.py
tests/test_main_addheader.py
tests/test_main_addheader_merge.py
tests/test_project.py
tests/test_report.py
tests/test_util.py

In the tool codebase, there are quite some usages of hacks to circumvent SPDX tags and copyright lines to be false-positively detected or to also trigger warnings and errors.
For example, after the first commit in this PR that removed all these hacks, the output was the following:
```
reuse lint
reuse._util - ERROR - Could not parse 'LicenseRef-custom",'
reuse.project - ERROR - 'tests/conftest.py' holds an SPDX expression that cannot be parsed, skipping the file
reuse._util - ERROR - Could not parse 'GPL-3.0-or-later}"'
reuse.project - ERROR - 'tests/test_util.py' holds an SPDX expression that cannot be parsed, skipping the file
reuse._util - ERROR - Could not parse 'Apache-1.0+"'
reuse.project - ERROR - 'tests/test_report.py' holds an SPDX expression that cannot be parsed, skipping the …
```

Use ignore blocks instead of hacks

---

.pre-commit-config.yaml
CHANGELOG.md
poetry.lock
pyproject.toml
requirements-dev.txt

Ran `pre-commit autoupdate`. This specifically fixes an issue with Black
formatting causing issues.

Bump pre-commit versions

---

src/reuse/_comment.py

Add comment style support for CODEOWNERS files used to define
permissions in code repositories. The syntax is mainly based on the
syntax from the .gitignore files. More on this is available in the
documentation by GitHub:
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#codeowners-syntax
Signed-off-by: Nico Rikken <nico.rikken@fsfe.org>

CODEOWNERS file comment support

---

src/reuse/_comment.py

Add comment definition for Less style sheet language. More on this
format on the official website: https://lesscss.org/ Although Less
supports an inline comment syntax (`//`) besides the default CSS
comment syntax (`/*` `*/`). I decided to go for maximum
compatibility with the original CSS syntax and use the CSS comment
syntax.
Signed-off-by: Nico Rikken <nico.rikken@fsfe.org>

Less style sheet syntax

---

src/reuse/_comment.py

Support the INI format syntax for `ansible.cfg` files. This file is used
to configure the Ansible software and can reside in multiple locations.
The INI format uses the hash sign (#) for comments that occupy an entire
line. The PythonCommentStyle is chosen to match this comment style.
More documentation about the Ansible Configuration Settings file is
available in the official documentation:
https://docs.ansible.com/ansible/latest/reference_appendices/config.html

feat: ansible.cfg comment style support

---

src/reuse/resources/exceptions.json
src/reuse/resources/licenses.json

3.18 has been released a few hours ago: https://github.com/spdx/license-list-XML/releases/tag/v3.18

Update SPDX license/exception list to 3.18

---

.pre-commit-hooks.yaml
CHANGELOG.md

Meson subprojects are (surprisingly, at least to me) ignored by default even if not a git submodule, so being able to pass `--include-meson-subprojects` is essential for being able to use `reuse`, including as a pre-commit hook. This is not currently possible on the user's end.
By moving `lint` out of `entry` and into `args`, users of the hook can override the args in order to pass options like `--include-submodules` or `--include-meson-subprojects` (these options need to be given before the subcommand `lint`).
Any users that currently override args will need to add `lint` to their `args` when they update the hook version. Such users are likely rare/nonexistent because `reuse lint` currently has no options that are useful in a pre-commit hook context.
The default behavior (with no `args` …

Allow overriding options for pre-commit hook

---

AUTHORS.rst
CHANGELOG.md
src/reuse/_util.py
tests/test_util.py

The Rust project is working to [adopt REUSE to annotate licenses](https://github.com/rust-lang/compiler-team/issues/519), but when working on the initial implementation I stumbled on #343. The Rust repository has LLVM as one of its submodules, and REUSE currently errors out on some of the LLVM comments:
```
reuse._util - ERROR - Could not parse 'Apache-2.0 WITH LLVM-exception                    *|'
reuse.project - ERROR - 'src/llvm-project/lldb/source/Plugins/Plugins.def.in' holds an SPDX expression that cannot be parsed, skipping the file                                                                      
```
As #343 correctly pointed out, the problem is that LLVM uses ASCII art "frames" for those code comments, like:
```c
/***********************************************************\ …
```

Find license identifiers in comments with ASCII art frames

---

pyproject.toml

For some reason this wasn't working for me, and black started formatting everything in `.tox`. Removing this config fixed it.

Remove unneeded exclude config for black

---

CHANGELOG.md
src/reuse/_comment.py
src/reuse/_util.py
tests/test_comment.py
tests/test_util.py

Related to #516, but doesn't really address it.
Fixes error when parsing
```
<p>Hello, world!</p>
```

Fix sameline multiline

---

CHANGELOG.md
src/reuse/_comment.py

Adds comment style VelocityCommentStyle for the template files of the
Apache Velocity project https://velocity.apache.org/ Most typical file
formats `.vst` and `.vm` for these files are assigned for this comment
style.
This PR relates to issue #553
The single line comments requires a more elaborate code change to
support trailing ` **`, so this change only contains the multi-line
format.

Apache Velocity template language comment style

---

README.md

You can [install reuse with MacPorts](https://ports.macports.org/port/reuse/)! This PR adds that information to the installation section of the readme.

Add MacPorts installation instructions

---

CHANGELOG.md
src/reuse/_util.py
tests/test_util.py

Fixes #292 
The only thing which is not supported is using `)` as an ending, because this is a valid ending for SPDX expressions (e.g., `SPDX-License-Identifier: (MIT OR 0BSD)`).

Strip special non-comment-style endings from regex matches

---

README.md

Changes:
- Add Alpine Linux URL.
- GNU Guix has bumped versions which are part of its URL.
- Fedora has changed its URL schema.
- The NixOS URL was especially to a now outdated version.
As an alternative, the growing list of different packages could be removed and only a link to repology.org next to a generic example - e.g. `apt-get install reuse` - could remain.

README.md: Fix Package Manager Links

---

CHANGELOG.md
README.md
docs/scripts.rst
docs/usage.rst
src/reuse/_comment.py
src/reuse/_main.py
src/reuse/header.py
tests/test_header.py
tests/test_main_annotate.py
tests/test_main_annotate_merge.py

Fixes #338 
Plan: Rename `addheader` to `annotate` to reduce confusion.
`annotate` keeps current behaviour: New header if none exists; replace header if exists.
Add `--no-replace` flag to not replace the header.
Instead of replacing the first header, add a new header before it. Do NOT pull
SPDX info from the 'old' first header.
```bash
$ reuse annotate --no-replace --license GPL-3.0
```
```python
#
#
#
#
#
#
#
```
->
```python
#
#
#
#
#
#
#
```

Rename `addheader` to `annotate`; add `--no-replace`

---

CHANGELOG.md
tests/conftest.py
tests/test_main_annotate.py

While starting to work on reuse-tool I first ran the tests and noticed an overwhelming flood of DEBUG outputs.
This PR is my attempt to improve the user experince of running the tests frequently by allowing for a commandline option `--loglevel <LEVEL>`. This does break one test that relies on log output, thus this test is skipped, if the loglevel is too high.
Feel free to suggest a place to put some instructions on how to use it (if it isn't self-explanatory), as I wasn't sure where an example call would fit best.

Add loglevel argument to pytest. [convenience feature]

---

CHANGELOG.md
poetry.lock

Replaces #649, closes #635 
I ran `poetry update certifi` to get around https://github.com/python-poetry/poetry/issues/2094 on Poetry 1.1

Bump certifi, adjust Poetry

---

pyproject.toml

otherwise they are found in, e.g., `/usr/lib/python3.11/site-packages/README.md`
Fixes #656

don't install docs top-level in site-packages

---

src/reuse/_comment.py

Scala uses the C comment style with `//` instead of `#` for both Scala 2 [1] and 3 [2].
[1] https://www.scala-lang.org/files/archive/spec/2.13/01-lexical-syntax.html#whitespace-and-comments
[2] https://docs.scala-lang.org/scala3/book/scala-for-python-devs.html#comments

Fix comment style for Scala

---

.github/workflows/pythonpackage.yaml

We want to see the results of all combinations in the `test` job and not abort the whole job if only one fails.
This way it's easier to see in a PR which combinations are problematic, so we don't have to fix them one-by-one.

Do not abort the whole test job if one combination in the matrix fails

---

docs/usage.rst

Fixes #664, kind of. #664 is not a bug; but the behaviour was not documented. This fixes that.

Document that meson subprojects are ignored by default

---

CHANGELOG.md
src/reuse/comment.py

This merge request implements a couple of requested format support.
Each format is in it's own commit to keep things clearly separated.
Fixes #575
Fixes #614
Fixes #616

New formats support

---

.github/workflows/test.yaml
.pylintrc
.readthedocs.yaml
CHANGELOG.md
Makefile
README.md
docs/conf.py
docs/requirements.txt
poetry.lock
pyproject.toml
src/reuse/_util.py
src/reuse/comment.py
src/reuse/header.py

Fixes #530 
This was surprisingly annoying. I thought Poetry was supposed to make life easier :weary: I'm stuck using Poetry v1.1 to maintain `poetry-core>=1.0.0` support, and it doesn't work quite as smoothly as later versions. Specifically, there was an endless loop for `sphinxcontrib.jquery`, which means I had to drop the RTD theme to preserve my patience for more important things.

Drop Python 3.6 support

---

CHANGELOG.md
src/reuse/comment.py

This adds one of the three supported comments styles for this format:
https://textile-lang.com/doc/textile-comments
If this is ever an issue for someone in the future, they would have to add support for the two native, custom types of comments.

Adds mapping for Textile (`.textile`) files #712

---

CHANGELOG.md
docker/Dockerfile
docker/Dockerfile-debian
docker/Dockerfile-extra

Fix #693 
gettext (msgfmt) was missing from the Docker images during build. This PR adds gettext during the setup phase. The actual Docker image size will not significantly be impacted as it's a multistage build.

Make translations available in Docker images

---

src/reuse/download.py

Adds a debugging statement to the license URL. Addresses the concern raised in https://github.com/fsfe/reuse-tool/issues/694
Signed-off-by: Nico Rikken <nico@nicorikken.eu>

chore: debug statement on license URL

---

docker/Dockerfile
docker/Dockerfile-debian
docker/Dockerfile-extra

Fixes the requirement that: Newer versions of git needs the 'git config --global --add safe.directory /data' setting to work in a container.
Here is an example to verify both the problem and the fix: 
Problem:
1) .Build an reuse image from latest main code, official branch:
` docker build -f docker/Dockerfile-debian -t reusetest_default .`
2). Run the code in reuse compliant project, I used my script project (https://github.com/janderssonse/janderscripts)
` docker run --rm --volume $(pwd):/data reusetest_default lint`
**Result**: Fails respecting .gitignore etc as the git config will fail and show warning '---no VCS'' etc.
Fix:
3). Now try the same dockerfile but with the added fix in this pr:
` docker build -f docker/Dockerfile-debian -t reusetest_with_git_add_data_safe .`
4).  Run on …

fix(docker): add git safe dir to data dir

---

src/reuse/project.py

This warning was incorrect when the directory was not a VCS repository. Reducing this to INFO and making the language more precise should fix that problem.

Adjust log message to be more accurate

---

CHANGELOG.md
src/reuse/comment.py

Add support of Visual Studio Code workspace files (which is based on JSON with Comment files)
Fixes #746

Add support for Visual Studio Code workspace file ".code-workspace"

---

CHANGELOG.md
src/reuse/comment.py

Add support for the Application Resource Bundle (.arb) files mostly used in Flutter to generate localisation.
Fixes https://github.com/fsfe/reuse-tool/issues/748

Add support for flutter Application Resource Bundle file ".arb"

---

src/reuse/_util.py

As shown in the examples of the SPDX specification (https://spdx.github.io/spdx-spec/v2.3/file-information/#8.8), the a copyright year range is not required to contain spaces around the dash character.
This patch allows zero or more spaces on each side of the dash, making all of the following year ranges being accepted by reuse: "2023"
"2022-2023"
"2022 - 2023"
"2022-  2023"
"2022  -2023"
Reuse still writes the copyright in a normalized "yyyy - yyyy" format.
Closes #647

Allow year ranges to contain space around the dash

---

CHANGELOG.md
src/reuse/comment.py

Add comment style for Jakarta Server Page (.jsp) files. The comment syntax is
`<%-- comment --%>` as observed in real code and found described in this
tutorial
https://www.digitalocean.com/community/tutorials/jsp-example-tutorial-for-beginners#jsp-comments
Signed-off-by: Nico Rikken <nico@nicorikken.eu>

feat: Jakarte Server Page (.jsp) comment style

---

CHANGELOG.md
src/reuse/comment.py

Support for `.aes` files which is a typical extension for AES-encrypted files.
Commenting is not possible for these files.
Signed-off-by: Nico Rikken <nico@nicorikken.eu>

feat: uncommentable AES encrypted files

---

src/reuse/_main.py

Apparently, argparse does not support suppression of help for subcommands and this will likely not change:
https://github.com/python/cpython/issues/67037
The simple, even if not quite as pretty solution is to just make the deprecation explicit instead of trying to suppress it.
Closes #739.

Explicitly state deprecation instead of trying to suppress it

---

.github/workflows/test.yaml
.pre-commit-config.yaml
CONTRIBUTING.md
poetry.lock
pyproject.toml
src/reuse/__init__.py
src/reuse/_format.py
src/reuse/_licenses.py
src/reuse/_main.py
src/reuse/_util.py
src/reuse/comment.py
src/reuse/download.py
src/reuse/header.py
src/reuse/init.py
src/reuse/lint.py
src/reuse/project.py
src/reuse/py.typed
src/reuse/report.py
src/reuse/spdx.py
src/reuse/supported_licenses.py
src/reuse/vcs.py
tests/conftest.py
tests/test_lint.py
tests/test_main.py
tests/test_project.py
tests/test_report.py

I'd been meaning to do this for a while. We have all these type annotations, but don't check whether they're valid.

Type checking with mypy

---

CHANGELOG.md
src/reuse/_main.py
src/reuse/project.py
tests/test_lint.py
tests/test_project.py

See rationale in #779 for reverting this behaviour.

Revert the mandatory order of precedence; display PendingDeprecationWarning

---

CHANGELOG.md
src/reuse/__init__.py
src/reuse/_util.py
src/reuse/project.py
src/reuse/report.py
tests/test_core.py
tests/test_project.py
tests/test_report.py

Since #778, the source information is incorrect. This was flagged before [here](https://github.com/fsfe/reuse-tool/pull/654#discussion_r1161900096).
Also fixes #753

Make sure the sources are correct when information is aggregated

---

CHANGELOG.md
src/reuse/comment.py

Typst is a typesetting program created in rust in the same vein of LaTeX.
the syntax for comments is [here](https://typst.app/docs/reference/syntax/#comments) and uses the same style as the C programming language for both single and multi-line comments, so a new style is not needed.

Add Typst file support (.typ)

---

.bumpversion.cfg
CHANGELOG.md
README.md
docs/conf.py
pyproject.toml
src/reuse/__init__.py

After the yanked 2.0.0 release, we're excited to announce our latest major version packed with new features and improvements! We've expanded our file type recognition, now including Fennel, CommonJS, Qt .pro, .pri, .qrc, .qss, .ui, Textile, Visual Studio Code workspace, Application Resource Bundle, Svelte components, AES encrypted files, Jakarta Server Page, Clang format, Browserslist config, Prettier config and ignored files, Flutter pubspec.lock, .metadata, Terraform and HCL, Typst and more.
We've also added the ability to detect SPDX snippet tags in files and introduced additional license metadata for the Python package. A new `--json` flag has been added to the `lint` command, marking the first step towards better integration of REUSE output with other tools.
Notably, …

Release 2.1.0

---

AUTHORS.rst
CHANGELOG.md
src/reuse/comment.py

Add the comment style for Julia.[^1] This supports both single-line comments and multi-line comments.
Also, single-line multi-line comments cannot be parsed with `CommentStyle.parse_comment()`, so I changed this to run `CommentStyle._parse_comment_multi()` first.
[^1]: https://docs.julialang.org/en/v1/base/punctuation/

Add Julia comment style

---

.pre-commit-hooks.yaml

Reuse specifying `language_version: python3` means that the hook is executed using the system `python3` version and it takes priority over the top level language configuration of the project unlesss the project added explicit override for the reuse hook.
E.g. with:
```yaml
default_language_version:
python: pypy3
```
all other Python3 `pre-commit` hooks I have would be running with `pypy3` with the exception of `reuse` enforcing `python3`.
Based on https://github.com/fsfe/reuse-tool/pull/132, reuse would support pypy outside of pre-commit.

.pre-commit-hooks.yaml: remove the language_version

---

AUTHORS.rst
CHANGELOG.md
src/reuse/comment.py

The current comment style for Fortran seems to target fixed form source code, where any character in col.1 would start a comment. The character usually is "c" or ''C".  
Free form source code, on the other hand, requires an "!" to start comments. Adding comments with a leading "c" is not supported if I'm not mistaken, sources would no longer compile, `reuse` would thus break the code.
This PR adds an additional comment style for modern free form Fortran and adjusts the selection to commonly used file extensions. While the easiest fix would have been to replace
```python
SINGLE_LINE = "c"
```
with
```python
SINGLE_LINE = "!"
```
I think it is more customary to have 'c' with fixed form source code, hence the additional style block.
Since the changes are minimal at best, I did not add a line …

Add modern Fortran comment style

---

AUTHORS.rst
CHANGELOG.md
src/reuse/_util.py
src/reuse/header.py
src/reuse/project.py

This prevents incidents of falsely detected copyright info
in binary files (and other uncommentable file types),
if they contain the word "Copyright" as plain-text.
This happened to me in the case of some JPG files, for example.
This also saves us from reading binary file contents unnecessarily.
... or are there ever cases where we want to detect plain-text in binary or uncommentable files?

Do not scan uncommentable files

---

CHANGELOG.md
src/reuse/lint.py
src/reuse/report.py
tests/test_lint.py
tests/test_report.py

Fix #672
As noted in the referenced issue, some error messages of `reuse lint` are not really helpful if your experience with REUSE and/or licensing is limited.
This PR attempts to improve the situation by adding a "Recommendations" section after the linting result, explaining the occured issues and how to best solve them (if there is an easy solution).
I'm not sure whether the position I implemented this in the code is ideal, but I liked that I could derive everything from the `report` object. Depending on what other issues we might want to explain, there might be better solutions, but I didn't invest many thoughts on this yet.
Possible blockers:
* The help texts should probably also go into the future JSON output. So #654 might need to be adapted, or this PR if JSON is added before. …

Add a "Recommendations" section in lint output based on found issues

---

AUTHORS.rst
CHANGELOG.md
src/reuse/project.py
src/reuse/vcs.py
tests/conftest.py

The current heuristic to detect submodules, which checks if a directory contains a .git file, is too simple. In some cases .git might instead be a directory. This happens for example with datalad subdatasets or, according to the git submodules man page, with independently cloned repositories:
> A repository that was cloned independently and later added as a submodule or old setups have the submodules git directory inside the submodule instead of embedded into the superprojects git directory.
This PR fixes this issue by getting a list of submodules from the .gitmodules file and comparing the paths with that instead.

Fix git submodule detection if .git is not a file

---

CHANGELOG.md
src/reuse/_licenses.py
src/reuse/_util.py
src/reuse/download.py
src/reuse/init.py
src/reuse/project.py
src/reuse/report.py
tests/test_download.py
tests/test_main.py

When initializing a new project that will use a custom license, the first step will fail because it currently handles only the list of supported license.
This pull request implements the handling for `LicenseRef-` so that it can also be used from the start.
The implementation will request a path to the license file so it can be copied over to the project.
Fixes #677

Add support for using LicenseRef- when initialising

---

src/reuse/resources/exceptions.json
src/reuse/resources/licenses.json

ran the following to make update: 
```bash
$ python .github/workflows/license_list_up_to_date.py  -d 
spdx-license-list-data latest version is v3.22
exceptions.json is not up-to-date, downloading newer release
licenses.json is not up-to-date, downloading newer release
```

update spdx licenses to fix github action failure

---

CHANGELOG.md
src/reuse/_main.py
src/reuse/_util.py
src/reuse/project.py
src/reuse/report.py
tests/test_lint.py
tests/test_main.py
tests/test_project.py
tests/test_report.py
tests/test_util.py

Fixes #803 by having better error handling.
Upstream PR to improve some exception catching: https://salsa.debian.org/python-debian-team/python-debian/-/merge_requests/123
After adding a duplicate Copyright field, the lint output looks like this:
```
$ reuse lint
usage: reuse [-h] [--debug] [--suppress-deprecation] [--include-submodules] [--include-meson-subprojects] [--no-multiprocessing] [--root PATH] [--version]
{annotate,download,init,lint,spdx,supported-licenses,supported-licences} ...
reuse: error: '.reuse/dep5' could not be parsed. We received the following error message: Duplicate field "Copyright" in paragraph number 1
```

Better error handling for DEP5 parse errors

---

.github/workflows/license_list_up_to_date.yaml
.github/workflows/pijul.yaml
AUTHORS.rst
CHANGELOG.md
README.md
src/reuse/_util.py
src/reuse/project.py
src/reuse/vcs.py
tests/conftest.py
tests/test_main.py
tests/test_project.py
tests/test_vcs.py

[Pijul](https://pijul.org) is a new VCS based on a theory of commutative patches. This commit adds support for Pijul to reuse-tool by implementing `VCSStrategyPijul`.

Add support for the Pijul VCS

---

CHANGELOG.md
src/reuse/_annotate.py
tests/test_main_annotate.py

The original behaviour of #823, but via a very roundabout way.

Remove --exit-if-unrecognised, add --fallback-dot-license

---

CHANGELOG.md
src/reuse/__init__.py

The .sl directory is used by Sapling (https://sapling-scm.com/) so
it should be handled like the other SCM directories.

Ignore .sl directory the same way as .hg.

---

CHANGELOG.md
src/reuse/comment.py

Zig supports C99 single line comments, but not C multi-line comments.
Fix the comment style for Hare by using ZigCommentStyle, instead of CCommentStyle.
I avoided adding support for zon (Zig Object Notation) files used by the Zig package manager, since it is still in its early stages.
Closes #837
Closes #888

Add support for Zig and fix Hare comment style

---

src/reuse/_licenses.py

There was a breaking change v0.7 -> v0.8 in `spdx/tools-python`, causing the link to the original location to be broken.
Replace the master branch with the actual commit at the time when the file was copied.
The chosen commit is 462e986, based on Github history (2017-06-15) and the commit date of the `_license.py` file (2019-04-14).
The commit can be verified using https://github.com/spdx/tools-python/commits/main/spdx/config.py, in case I got it wrong.

Fix the link to spdx/tools-python in _license.py

---

CHANGELOG.md
src/reuse/comment.py
tests/test_comment.py
tests/test_main_annotate.py

This allows specifying a new SINGLE_LINE_REGEXP property on a CommentStyle subclass, which provides more flexibility in parsing single line comments.
Fixes: <https://github.com/fsfe/reuse-tool/issues/637>

Allow specifying a regexp for matching a single line comment.

---

CHANGELOG.md
src/reuse/_util.py
src/reuse/comment.py
src/reuse/project.py
tests/test_project.py

No longer refuse to scan files with uncommentable file extensions

---

CHANGELOG.md
src/reuse/_annotate.py
tests/test_main_annotate.py

--style should work with unrecognised files

---

.bumpversion.cfg
CHANGELOG.md
README.md
docs/conf.py
pyproject.toml
src/reuse/__init__.py

Release 3.0.2

---

.github/workflows/test.yaml
CHANGELOG.md
src/reuse/comment.py

Assume  's' and 'S' sufixes for GNU Assembler, and 'asm' for NASM

---

CHANGELOG.md
src/reuse/comment.py

- Visual Studio solution file, `.sln`
- .NET project files: `.csproj`, `.fsproj`, `.vbproj`
- F# script files, `.fsx`
- MSBuild files, `.props` (such as `Directory.Build.props`)
While working with the tool, I've also noted that it can sometimes break files if they include UTF-8 BOM (which is, while not mandatory, pretty common in .NET ecosystem). This is a separate issue #384, though.

Add support for certain files from .NET ecosystem

---

CHANGELOG.md
src/reuse/comment.py

Fixes #942 
Code contributed by @lpechacek. Thanks!

Add support for Unix manual pages (`.man`)

---

CHANGELOG.md
src/reuse/comment.py

From https://docs.spring.io/spring-graphql/reference/request-execution.html#execution.graphqlsource.schema-resources
> By default, the Boot starter [looks for schema files](https://docs.spring.io/spring-boot/docs/3.1.5/reference/html/web.html#web.graphql.schema) with extensions ".graphqls" or ".gqls" under the location classpath:graphql/**, which is typically src/main/resources/graphql.
This PR adds ´.graphqls´ and ´.gqls´ to the list of supported files.

Add support to .graphqls in addition to .graphql

---

CHANGELOG.md
src/reuse/header.py
tests/test_header.py

Support annotating a file that contains only a shebang

---

CHANGELOG.md
src/reuse/__init__.py
tests/test_project.py

Related to #881 and https://github.com/fsfe/reuse-docs/issues/139

Ignore COPYING and LICENSE as exact matches or with extensions

---

CHANGELOG.md
src/reuse/comment.py

Not sure if this has been discussed before, but all Java `.properties` files have a similar structure (and support Python-like comments), so it makes sense to support them all at once.

Add support for any Java .properties

---

CHANGELOG.md
docs/man/reuse-lint.rst
src/reuse/lint.py
src/reuse/project.py
tests/test_lint.py

Adds an '-line' or '-l' option to the 'lint' command. Prints a line for
each error, starting with the file to which the error belongs.
This output can be a starting point for some parsers, in particular ones
that implement something similar to Vim errorformat parsing.
Related to https://github.com/fsfe/reuse-tool/issues/925, needed for #578
Additional work needed:
FileReports. This requires additional investigation.
Signed-off-by: Nico Rikken <nico@nicorikken.eu>

feat: lint output per line

---

CHANGELOG.md
src/reuse/comment.py

1. Interpret .cls files as LaTeX.
2. Some TeX editors and other programs use a `% !TEX` and `% !BIB` macro at the top of .tex and .bib files, respectively, so I added those as 'shebangs' in the comment style classes. That way, the comment block is injected after the macros.

TeX file adjustments.

---

CHANGELOG.md
pyproject.toml

I have recently taken maintenance of reuse in Fedora, and these are fixes for two minor issues I ran into while packaging the most current version (3.0.2).
1. `CONTRIBUTING.md` is missing from the sdist archive, but is included/used by Sphinx while building docs. So currently the docs cannot be built from sdist.
2. Our pytest invocation does some black magic with PYTHONPATH, and with the current configuration it leads to bunch of `ImportMismatchError`s when the tests are being collected. Swithing to `importlib` mode (which should be [the blessed way nowadays](https://docs.pytest.org/en/stable/explanation/goodpractices.html#which-import-mode)) fixes them and allows the tests to run (successfully on my machine).
This change looks fine to me, but I'm fine with dropping it if it would cause …

Improve source distribution

---

CHANGELOG.md
src/reuse/comment.py

* .taprc for node-tap
* .zshrc for zsh
* .t for perl test files
* .bats for BATS test files

Add four new file(types) in the automatically supported files

---

CHANGELOG.md
src/reuse/project.py
tests/test_project.py

This was previously undefined behaviour. Now that it has been defined, there is no need to raise a warning to the user.
Fixes #1010

Remove deprecation warning from DEP5 aggregation

---

CHANGELOG.md
docs/man/reuse-annotate.rst
src/reuse/comment.py
tests/test_comment.py
tests/test_header.py
tests/test_main_annotate.py

C and C++ features different comment styles:
- only multi-line `/* */` comment is valid in traditional C89
- C++ also supports `// ` single line comments from its beginning
- C started to support C++-style `// ` comments in C99
For this reason, multi-line `/* */` is often named C-style comment and single-line `// ` is often named C++-style comment.
In current implementation, there were only a "CCommentStyle" with `/* */` and `// ` support, used for both C and C++ files (also used by quite many other file types). 
Therefore:
- Rename CCommentStyle as CppCommentStyle
- Create a new CCommentStyle with only `/* */` support
- Remove redundant CssCommentStyle (same as new CCommentStyle)
- Associate *.c and *.h with CCommentStyle
Caution:
- this (slightly) changes *.c and *.h comments (by …

comment: C, Cpp and Css styles reorganization (big)

---

changelog.d/added/comment-j2.md
src/reuse/comment.py

[Ansible](https://www.ansible.com) commonly uses `.j2` file extensions for [Jinja2](https://jinja.palletsprojects.com) template files it relies on.
Link: <https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_templating.html>
---
- ~~[ ] Added self to copyright blurb of touched files.~~ addition pending in another MR, not added here to avoid conflicts
- ~~[ ] Wrote tests.~~
- ~~[ ] Documented my changes in `docs/man/` or elsewhere.~~

comment: threat .j2 files as Jinja2

---

changelog.d/changed/comment_gnu_as.md
changelog.d/changed/comment_gnu_ld.md
src/reuse/comment.py

As well described by sourceware website [1]:
There are two ways of rendering comments to as:
- Anything from `/*` through the next `*/` is a comment.
- The line comment character is target specific
We therefore better should use the C style comment instead of any single-line comment which can't fit every cases.
Wikipedia [2] provides a list of target-specific GNU as single-line comments:
- A hash symbol (#) — i386, x86-64, i960, 68HC11, 68HC12, VAX, V850, M32R,
PowerPC, MIPS, M680x0, and RISC-V
- A semicolon (;) — AMD 29k family, ARC, H8/300 family, HPPA, PDP-11,
picoJava, Motorola, and M32C
- The at sign (@) — 32-bit ARM
- A double slash (//) — AArch64
- A vertical bar (|) — M680x0
- An exclamation mark (!) — Renesas SH
Hash symbol is currently used, this PR make it `/* */`
As per …

comment: fix GNU ld and as files

---

.github/workflows/jujutsu.yaml
AUTHORS.rst
README.md
changelog.d/added/jujutsu.md
src/reuse/_util.py
src/reuse/vcs.py
tests/conftest.py
tests/test_main.py
tests/test_project.py
tests/test_vcs.py

Although it uses .gitignore, Jujutsu has support for repositories without git ("non-colocated"), which we can't use "git ls-files" on
jj has its own command for listing out tracked files ("jj files"), and we can use it to determine ignored files in a similar way to Pijul
Fixes: fsfe/reuse-tool#711
changed files.

feat(vcs): Add Jujutsu support

---

changelog.d/added/new-prefixes.md
changelog.d/fixed/prefix-merge.md
docs/man/reuse-annotate.rst
src/reuse/_util.py
tests/test_main_annotate_merge.py
tests/test_util.py

Added new copyright style with spdx and string c  as per #948

---

changelog.d/changed/comment-cargo-lock.md
src/reuse/comment.py

`Cargo.lock` files are TOML and allow comments. Cargo is clever and preserves these comments when it makes changes to the lock file.
changed files.

Allow Python-style comments in Cargo.lock files

---

tests/conftest.py

Apparently LANGUAGE has precedence over LC_ALL. By setting it to an empty string, LC_ALL takes precedence again, and we forcefully use the English translations.
changed files.

Override LANGUAGE when running tests

---

.pre-commit-hooks.yaml
.pylintrc
AUTHORS.rst
README.md
changelog.d/added/lint-file.md
docs/conf.py
docs/man/reuse-lint-file.rst
docs/man/reuse-lint.rst
pyproject.toml
src/reuse/_lint_file.py
src/reuse/_main.py
src/reuse/_util.py
src/reuse/global_licensing.py
src/reuse/lint.py
src/reuse/lint_file.py
src/reuse/project.py
src/reuse/report.py
tests/conftest.py
tests/resources/fake_repository/src/custom.py
tests/resources/fake_repository/src/exception.py
tests/resources/fake_repository/src/multiple_licenses.rs
tests/test_lint.py
tests/test_main.py
tests/test_project.py
tests/test_report.py

Added `lint-file` subcommand to allow people to lint specified file(s). In the command line, you can run `reuse lint-file <files>`. For example, `reuse lint-file src/reuse/download.py src/reuse/_annotate.py`. If you only run `reuse lint-file` with no files listed, then it will lint all files (as if you were just running `reuse lint`).
Let @SMoraisAnsys or I know if you have any questions or concerns! This PR addresses the suggestions in #903.
Here is a picture of running `reuse lint-file` in the command line with a file that doesn't exist (dne_file.py), two files that exist and are compliant, and one file that exists but is not compliant (empty_file.py):
changed files.

feat: lint-file subcommand

---

changelog.d/changed/unspecly-changes.md
src/reuse/__init__.py
tests/test_project.py

Fixes #1032.
Also ignore such files separated by a dash instead of a full stop.
Also ignore the UK spelling LICENCE.
changed files.

Be more lenient in ignoring LICENSE and COPYING-like files

---

AUTHORS.rst

- [] Added a change log entry in `changelog.d/<directory>/`.
changed files.

Remove duplicates

---

changelog.d/changed/reuse-toml-ignored.md
changelog.d/fixed/performance.md
changelog.d/fixed/source-bug.md
src/reuse/_main.py
src/reuse/covered_files.py
src/reuse/global_licensing.py
src/reuse/project.py
src/reuse/report.py
src/reuse/vcs.py
tests/conftest.py
tests/test_covered_files.py
tests/test_global_licensing.py
tests/test_main.py
tests/test_project.py

Fixes #1033 
Relevant to https://github.com/fsfe/reuse-website/pull/85
This is my attempt at fixing #1033. It necessitates a whole lot more shuffling things around than I had anticipated.
changed files.

Fix the REUSE.toml performance regression (+ do a whole lot of refactoring)

---

docs/man/reuse-lint.rst

The usage of 'the REUSE.toml file' was incorrect. There may be multiple ones. The new language use is more correct and adds helpful context.
Issue raised in #1040
changed files.

man: Clarify where REUSE.toml may be located

---

changelog.d/changed/no-license-reuse-toml.md
src/reuse/__init__.py
src/reuse/covered_files.py
src/reuse/global_licensing.py
tests/resources/REUSE.toml
tests/test_covered_files.py

As discussed on 2024-07-05
Fixes #1040 
changed files.

Licensing header is not needed in REUSE.toml

---

.pylintrc
poetry.lock
src/reuse/global_licensing.py

RTD compilations of the `latest` branch have been broken for two weeks. I have reported this upstream at https://github.com/readthedocs/readthedocs.org/issues/11624
For reasons that are beyond me, re-generating `poetry.lock` fixes the problem.
changed files.

Fix RTD compilations

---

README.md
src/reuse/_main.py

Fixes #1048, and contains some more fixes.
changed files.

Improve documentation of subcommands

---

.github/workflows/gettext.yaml
src/reuse/cli/annotate.py
src/reuse/cli/common.py
src/reuse/cli/convert_dep5.py
src/reuse/cli/download.py
src/reuse/cli/lint.py
src/reuse/cli/lint_file.py
src/reuse/cli/main.py
src/reuse/cli/spdx.py

This is a lot cleaner, and has better performance benefits. Commands like 'download' do not always require a project object. Now, if the code never touches 'obj.project', the object is never created.
Apart from performance benefits, it also means that irrelevant errors spawned from creation of the project object are sidestepped, because the object is never instantiated (in some cases).
changed files.

Generate project object on demand

---

changelog.d/added/comment-flake-envrc.md
src/reuse/comment.py

I've added the `.envrc` (used by at least [direnv](https://direnv.net/)) and the nix flake lock file (`flake.lock`) to the recognized extensions. I've not added an entry in the changelog, as it seemed to tiny to be included in it (let me know if I should include it.). 
changed files.

Add `.envrc` and `flake.lock` extensions

---

src/reuse/cli/annotate.py
src/reuse/cli/download.py
src/reuse/cli/lint_file.py

Provide helpful comment to translators

---

changelog.d/added/comment-cabal.md
src/reuse/comment.py

This PR adds `.cabal` and `cabal.project` as recognized file types for comments. These files are used by the [Cabal](https://www.haskell.org/cabal/) build tool.
changed files.

Add `.cabal` and `cabal.project` as recognised file types for comments

---

changelog.d/added/comment-cabal.md
src/reuse/comment.py

Fixes broken `.cabal` files by adding a shebang specification per https://github.com/fsfe/reuse-tool/pull/1089#issuecomment-2416476098.
changed files.

Add shebang for `.cabal` files

---

changelog.d/fixed/plain-format-output-new-line-fix.md
src/reuse/lint.py

With this PR,
```
📺 carmenbianca reuse-tool $ reuse lint
* Bad licenses: 0
* Deprecated licenses: 0
* Licenses without file extension: 0
[...]
```
becomes
```
📺 carmenbianca reuse-tool $ reuse lint
* Bad licenses: 0
* Deprecated licenses: 0
* Licenses without file extension: 0
[...]
```
changed files.

Get rid of newline at start of lint output

---

src/reuse/__init__.py
src/reuse/_annotate.py
src/reuse/cli/common.py
src/reuse/comment.py
src/reuse/exceptions.py
src/reuse/global_licensing.py
src/reuse/header.py
src/reuse/project.py
tests/test_comment.py
tests/test_global_licensing.py
tests/test_header.py
tests/test_project.py

Refactor exceptions

---

src/reuse/__init__.py
src/reuse/_annotate.py
src/reuse/_util.py
src/reuse/cli/annotate.py
src/reuse/cli/common.py
src/reuse/cli/spdx.py
src/reuse/copyright.py
src/reuse/covered_files.py
src/reuse/download.py
src/reuse/extract.py
src/reuse/global_licensing.py
src/reuse/header.py
src/reuse/project.py
src/reuse/report.py
src/reuse/vcs.py
tests/conftest.py
tests/test_cli_annotate.py
tests/test_copyright.py
tests/test_extract.py
tests/test_global_licensing.py
tests/test_project.py

`_util.py` and `__init__.py` are full of constants. I want to clean this up to have better separation of concerns.
changed files.

Refactor constants

---

AUTHORS.rst
changelog.d/fixed/license-overriding-global-name.md
src/reuse/project.py
tests/test_project.py

Fixes https://github.com/fsfe/reuse-tool/issues/1057
changed files.

Fix global licensing being ignored with a .license file

---

changelog.d/fixed/strip-plus.md
src/reuse/_util.py
src/reuse/cli/download.py
src/reuse/report.py
tests/test_cli_download.py

Fix downloading `SPDX-IDENTIFIER+`

---

.github/workflows/docker.yaml
.github/workflows/jujutsu.yaml
.github/workflows/license_list_up_to_date.yaml
.github/workflows/pijul.yaml
.github/workflows/test.yaml
.github/workflows/third_party_lint.yaml

Use Ubuntu 24.04 images

---

AUTHORS.rst
changelog.d/added/comment-gperf.md
src/reuse/comment.py

Add .gperf ([GNU gperf](https://www.gnu.org/software/gperf/)) as a recognised file type for comments.
changed files.

Add .gperf as a recognised file type for comments

---

CONTRIBUTING.md

Fixes #1122, sort of.
This PR doesn't structurally change anything. It explains everything a little better, and removes the obligation from the contributor to get all the annoying things right. Most of the checks exist for the _maintainers_, not for the contributors.
Fixing all the annoying stuff is the responsibility of the maintainers.
changed files.

Improve contribution guide lines

---

AUTHORS.rst
docs/scripts.rst

The current example does not follow renames which I think should be included to know the very first time the file was introduced.
For some reason, `git log --reverse --follow` does not work properly. So reversed it to use `tail` instead of `head`.
I added an extra section but it might be worth to add it to the existing examples instead.
changed files.
>  - [ ] Added a change log entry in `changelog.d/<directory>/`.
I feel that the changes are too small and do not affect the tool itself, so I did not add one. If you disagree, I'll be happy to add a changelog entry.

Add helper script snippet for following renames

---

AUTHORS.rst
changelog.d/added/erlang-elixir-gleam.md
src/reuse/comment.py

Adds support for comments for the most used BEAM languages:
- Erlang
- Elixir
- Gleam
changed files.

feat(BEAM): Add support for Erlang, Elixir, and Gleam comments

---

.github/workflows/close_inactive_issues.yaml

This will help with keeping the repo in a healthy state. Note that while this does contain a message for marking PRs as stale and closing them, it doesn't currently do so because the timeframes for that are set to -1. I just added the text to make activating it as painless as possible if we ever decide to do so.
Also, this will only touch 5 issues per run, so the pings will get spread out nicely. We can increase the number once it's handled all issues once or we can leave it as is until we notice a bottleneck.

Add Github action for closing stale issues

---

src/reuse/comment.py

The two comment styles functionally identical, except for the shebang.
Closes #1152.

Replace ErglangCommentStyle with TexCommentStyle

---

Makefile
changelog.d/fixed/translations.md

Apparently globstar patterns ('**/*') are not supported in Make. Using `find` circumvents this problem.
Fixes #1214
changed files.

Correctly include all gettext strings in .pot file

---

AUTHORS.rst
changelog.d/fixed/lint-help.md
src/reuse/cli/lint.py

This is #1212, re-opened. I somehow messed up pushing to the branch, and irreperably closed the PR.
changed files.

Fix lint subcommand's help message formatting

---

changelog.d/fixed/fix-format-lines.md
src/reuse/lint.py
tests/conftest.py
tests/test_lint.py

Fixes a bug mentioned in #1248 where a newline was missing.
I'd like to more universally sort by path.
changed files.

Fix and improve `reuse lint --lines`

---

changelog.d/fixed/performance-regex.md
src/reuse/extract.py

For reasons that are a little beyond me at the moment, but which are probably very obvious, the following line in the Linux kernel took 9 seconds to match:
```
* Portions Copyright (C) 2004-2005 Christoph Hellwig              *
```
The altered regex is sufficiently swift.
changed files.

Fix a regex that was occasionally very slow
