fsfe/reuse-tool

src/reuse/_format.py
src/reuse/_main.py
src/reuse/_util.py
src/reuse/lint.py
src/reuse/project.py
src/reuse/report.py
src/reuse/spdx.py
tests/test_project.py

Reduce verbosity of `reuse --help` and restructure the addition of subparsers

---

src/reuse/_comment.py
tests/test_comment.py

This will be necessary for creating and parsing headers.

Create method of creating and parsing comments

---

src/reuse/_util.py
src/reuse/download.py
src/reuse/lint.py
src/reuse/spdx.py
tests/test_util.py
tox.ini

Implement PathType to replace argparse.FileType

---

setup.py
src/reuse/_util.py
src/reuse/lint.py
src/reuse/project.py
src/reuse/report.py
tests/test_report.py

Fixes #16 
The tests pass, so I _think_ I did everything correctly. But I'll need to review this more carefully before proceeding.

Removed spdx-tools dependency

---

CHANGELOG.rst
src/reuse/_util.py
tests/test_project.py
tests/test_report.py
tests/test_util.py

Handle all variants of copyright tags

---

.reuse/dep5
MANIFEST.in
Makefile
docs/authors.rst
docs/history.rst
docs/index.rst
docs/readme.rst
src/reuse/project.py

See https://github.com/fsfe/reuse-docs/issues/36 and https://github.com/fsfe/reuse-docs/issues/37

Make the source tarball REUSE-compliant

---

src/reuse/download.py
tests/test_download.py
tests/test_main.py

Fixes #33 
Would also be nice if it said which directory the file was placed.

Add newline after download output

---

README.md

Update license section of README

---

README.md
src/reuse/__init__.py
src/reuse/_main.py
src/reuse/lint.py
tests/test_main.py

Show version of REUSE Spec in tool

---

.gitignore
Makefile
docs/conf.py
docs/index.rst
requirements.txt

 Generate apidoc without additional build step 

---

src/reuse/lint.py
src/reuse/report.py
tests/test_lint.py

I have very slightly tweaked the output of `reuse lint` to be more concise.

Improved lint

---

src/reuse/_comment.py

* Shell
* Nix (https://nixos.org/nix/)
* Elixir
Useful and missing, but too hard to add from the GitHub editor:
* Erlang + TeX
* OCaml

Add a couple of comment formats

---

AUTHORS.rst
CHANGELOG.md
src/reuse/_comment.py
tests/test_comment.py

* TeX:
* LaTeX
* Erlang
* ML:
* OCaml
* SML
(Continuation of #63)

Add new comment styles

---

.pylintrc
src/reuse/download.py
src/reuse/init.py
src/reuse/project.py
tests/test_main.py

Add some helpful messages referring to the SPDX License List

---

CHANGELOG.md
README.md
requirements.txt
setup.py
src/reuse/_main.py
src/reuse/header.py
src/reuse/templates/default_template.jinja2
src/reuse/templates/default_template.jinja2.license
tests/conftest.py
tests/test_header.py
tests/test_main.py

Add initial support for templates

---

CHANGELOG.md
requirements.txt
setup.py
src/reuse/_comment.py
src/reuse/header.py
tests/conftest.py
tests/test_main.py

Fixes #74. Also slightly addresses #73.

Handle binary and .license files

---

AUTHORS.rst
CHANGELOG.md
src/reuse/header.py
tests/test_main.py

Add --explicit-license to addheader

---

.editorconfig
CHANGELOG.md
docs/conf.py
docs/index.rst
docs/usage.rst
docs/usage.rst.license
src/reuse/__init__.py
src/reuse/_comment.py
src/reuse/_main.py
src/reuse/project.py
src/reuse/templates/default_template.jinja2.license
tests/test_project.py

Add usage documentation

---

CHANGELOG.md
src/reuse/project.py

Handle an additional DEP-5 syntax error

---

CHANGELOG.md
docs/usage.rst
src/reuse/_main.py
src/reuse/header.py
src/reuse/lint.py
src/reuse/project.py
src/reuse/spdx.py
tests/conftest.py
tests/test_lint.py
tests/test_main.py

add --include-submodules to lint

---

CHANGELOG.md
src/reuse/_comment.py

Add support for .kt and .xml

---

CHANGELOG.md
src/reuse/_comment.py

Add .yaml/.yml support

---

CHANGELOG.md
src/reuse/report.py
tests/test_report.py

Fixes #82
Fairly simple PR really

Bad licenses can also be missing

---

CHANGELOG.md
src/reuse/report.py
tests/test_report.py

I want to do some tinkering on report.py. This appendage was getting in the way.

Remove FileReportInfo

---

.github/workflows/latesttag.yml

Create a workflow for verifying latest tag

---

CHANGELOG.md
docs/usage.rst
src/reuse/_comment.py
src/reuse/_util.py
tests/test_util.py

Support BibTex comment style

---

CHANGELOG.md
src/reuse/_util.py
src/reuse/header.py
tests/test_main.py

addheader: Do not create a .license.license chain

---

CHANGELOG.md
docs/usage.rst
src/reuse/_comment.py
src/reuse/_util.py
tests/resources/fake_repository/src/source_code.jinja2

Fixes #156 
Not entirely happy with this PR. I'd hate having to manually edit `_END_PATTERN` every time.

Support Jinja2 comment style

---

.github/workflows/pythonpackage.yml
Dockerfile
Makefile
requirements-dev.txt
requirements.txt

Tinkered a bit with the Dockerfile. This was challenging because `COPY . /reuse-tool/` somehow takes ages on my system.
I split out the commands and added a `CMD` at the end, which is a default command if no custom command is supplied.

Improve Dockerfile

---

.bumpversion.cfg
AUTHORS.rst
CHANGELOG.md
docs/conf.py
docs/usage.rst
po/de.po
po/it.po
setup.py
src/reuse/__init__.py
src/reuse/_comment.py
src/reuse/_util.py
src/reuse/header.py
tests/resources/fake_repository/src/source_code.jinja2
tests/test_header.py
tests/test_util.py

Cherry-picked some commits to create a new patch release.

Release 0.8.1

---

.pre-commit-hooks.yaml
CHANGELOG.md
README.md

Fixes #212.
Great suggestion by @Flameeyes. Implementing this was super easy. This should also be added to the documentation on https://reuse.software/dev/

Add pre-commit hook

---

CHANGELOG.md
docs/usage.rst
docs/usage.rst.license
src/reuse/_main.py
src/reuse/header.py
tests/test_main.py

Add --single-line and --multi-line flags to addheader

---

.github/workflows/latesttag.yml
.github/workflows/license_list_up_to_date.py
.github/workflows/license_list_up_to_date.yml
src/reuse/_licenses.py
src/reuse/resources/exceptions.json
src/reuse/resources/licenses.json

This serves as a good reminder to keep those files up-to-date.

Create a workflow that verifies whether the license lists are up-to-date

---

README.md

This adds a ~1min GIF with a demo of a few commands to make the example repository REUSE compliant.
I've created this with [demo-magic](https://github.com/paxtonhare/demo-magic) and SimpleScreenRecorder, so we can easily change commands and create screencasts for other procedures.

Add screencast for tool commands

---

src/reuse/resources/exceptions.json
src/reuse/resources/licenses.json

Signed-off-by: Paul Spooren <mail@aparcar.org>

ressources: update to 3.10-16-gd252819 

---

Makefile

Downloads the latest {licenses, exceptions}.json from
spdx/license-list-data and stores them in place.
Signed-off-by: Paul Spooren <mail@aparcar.org>

make: add convenience function to update resources

---

.github/workflows/pythonpackage.yml
setup.py
tox.ini

It's in alpha, but it would be good to test.

Add Python 3.9 to tests

---

.pylintrc
CHANGELOG.md
Makefile
requirements-dev.txt
requirements.txt
setup.py
src/reuse/_util.py
src/reuse/header.py
src/reuse/report.py
tests/test_comment.py
tests/test_download.py
tests/test_header.py

This bump keeps everything in sync with upstream dependencies. Pylint is being annoying as usual.

Bump requirements.txt and requirements-dev.txt

---

tests/conftest.py
tests/test_comment.py
tests/test_main.py
tests/test_project.py
tests/test_vcs.py

When the tests are run, a good portion of them are skipped. I wanted to investigate whether this causes any issues. It didn't, but I refactored the tests to have no skips whatsoever.

Reduce test skips to zero

---

src/reuse/_comment.py

Here is a description of what a LaTeX package is:
https://www.overleaf.com/learn/latex/Understanding_packages_and_class_files

Add support for LaTeX package files (.sty)

---

CHANGELOG.md
Dockerfile
Dockerfile-extra

Use the latest stable alpine version.

Bump alpine to 3.13

---

src/reuse/_comment.py

Nothing important for sure, just stumbled upon it.

Support for Supercollider files

---

src/reuse/_comment.py

This solves #365 .
([previous/deprecated PR](https://github.com/fsfe/reuse-tool/pull/370))

Support Nimble files

---

CHANGELOG.md
docs/usage.rst
src/reuse/lint.py
tests/test_main.py

Add lint --quiet flag

---

po/es.po

A few translations that needed corrections.

A few corrections

---

.github/workflows/prettier.yaml
.github/workflows/pythonpackage.yaml
.pre-commit-config.yaml
.prettierignore
.prettierrc.yaml
CHANGELOG.md
CONTRIBUTING.md
Makefile
README.md

Life gets a lot easier when you let auto-formatters do all the formatting for you. This is a simple QOL addition.

Add prettier to the project

---

CHANGELOG.md
src/reuse/_comment.py

Adding support for .sbt files.

---

.github/workflows/latesttag.py
.github/workflows/license_list_up_to_date.py

Make license_list_up_to_date.py actually fail when it fails

---

.github/workflows/prettier.yaml
.github/workflows/pythonpackage.yaml

#491 is running all tests twice, which is just a little much.

Don't run CI on every single push

---

CHANGELOG.md
src/reuse/header.py

This applies to at least V-Lang scripts.

Preserve shebang for more script files

---

.pre-commit-config.yaml
.pylintrc
Makefile
pyproject.toml
requirements-dev.txt
requirements.txt
setup.py
src/reuse/_comment.py
src/reuse/_licenses.py
src/reuse/_main.py
src/reuse/_util.py
src/reuse/download.py
src/reuse/header.py
src/reuse/lint.py
src/reuse/project.py
src/reuse/report.py
src/reuse/spdx.py
src/reuse/supported_licenses.py
tests/conftest.py
tests/test_comment.py
tests/test_download.py
tests/test_header.py
tests/test_lint.py
tests/test_main.py
tests/test_main_addheader.py
tests/test_project.py
tests/test_report.py
tests/test_util.py
tests/test_vcs.py

This should not change any functionality, just improve code quality and enable better future code quality by using more sensible checks.

Improve pylint config

---

README.md

Updated link for GNU Guix to version 0.14.0

Add updated hyperlink for GNU Guix

---

CHANGELOG.md
src/reuse/_comment.py

Added support for Vimscript files (`.vim`)

---

CHANGELOG.md
src/reuse/header.py
tests/test_main_addheader.py

Add --recursive flag to addheader

---

CHANGELOG.md
src/reuse/_util.py

This should fix #440 by simply expanding the copyright detection mechanism.

Fix copyright detection

---

CHANGELOG.md
setup.py

Update the status to better reflect the project state. The release of
version 1.0.0 also signifies this status.
Closes #381
Signed-off-by: Nico Rikken <nico.rikken@fsfe.org>

PyPI Development Status to Production/Stable

---

AUTHORS.rst
CHANGELOG.md
src/reuse/_comment.py

Is that all that's needed for closing #524?

Make .pem files uncommentable

---

AUTHORS.rst
src/reuse/header.py

Add support for PHP header

---

.github/workflows/docker.yaml
.github/workflows/prettier.yaml
.github/workflows/pythonpackage.yaml
CONTRIBUTING.md
README.md

Replaces #459 
I'm going to take charge in this and just implement the changes. The master/main branch may be broken for a few minutes as I fix any potential issues.

Communicate change from master to main

---

AUTHORS.rst
CHANGELOG.md
src/reuse/_comment.py

Substitutes #584 
Closes #583
I didn't have write access to the branch, so I'm opening a separate PR.

Add xquery comment style

---

.bumpversion.cfg
README.md

Fixes https://github.com/fsfe/reuse-tool/issues/609

Don't use latest tag in pre-commit

---

.github/workflows/pythonpackage.yaml
CHANGELOG.md

Signed-off-by: Carmen Bianca Bakker <carmenbianca@fsfe.org>

Enable tests using Python 3.11

---

.pre-commit-config.yaml

Fixed in https://github.com/PyCQA/isort/pull/2078
Signed-off-by: Carmen Bianca BAKKER <carmenbianca@fsfe.org>

Fix isort pre-commit

---

pyproject.toml

Still works absolutely fine like this.

Reduce poetry-core dependency to >=1.0.0

---

.pre-commit-config.yaml

existing URL is being redirected: 
```
❯ curl -I  https://github.com/ambv/black
HTTP/2 301 
server: GitHub.com
date: Fri, 10 Feb 2023 18:03:47 GMT
content-type: text/html; charset=utf-8
vary: X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, Accept-Encoding, Accept, X-Requested-With
location: https://github.com/psf/black
cache-control: no-cache
strict-transport-security: max-age=31536000; includeSubdomains; preload
x-frame-options: deny
x-content-type-options: nosniff
x-xss-protection: 0
referrer-policy: origin-when-cross-origin, strict-origin-when-cross-origin
content-security-policy: default-src 'none'; base-uri 'self'; block-all-mixed-content; child-src github.com/assets-cdn/worker/ gist.github.com/assets-cdn/worker/; connect-src 'self' uploads.github.com …
```

update black URL to current (existing is redirected)

---

.gitignore
CONTRIBUTING.md
README.md
docs/conf.py
docs/index.rst
pyproject.toml
src/reuse/__init__.py

Tiny documentation fixes

---

README.md
pyproject.toml

Add Linus as maintainer

---

.github/workflows/gettext.yaml
CONTRIBUTING.md
README.md

Make translatable via weblate

---

CHANGELOG.md
src/reuse/resources/exceptions.json
src/reuse/resources/licenses.json

40 new licenses and exceptions have been added in this release.

Update SPDX license/exception list to v3.20

---

CHANGELOG.md

Add some change log entries

---

CONTRIBUTING.md
Makefile

Related to #722 
Fixes problem introduced in #715, which had prior been fixed in #673, where it was introduced in #648 :sweat_smile:

Don't use poetry>1.1 features

---

CHANGELOG.md
src/reuse/resources/exceptions.json
src/reuse/resources/licenses.json

Update SPDX license/exception list to v3.21

---

CHANGELOG.md

Yank 2.0.0 in change log

---

.github/workflows/gettext.yaml

Update .pot via CI

---

Makefile

Since a while it is tracked by Git.

Do not remove .pot file

---

.github/workflows/test.yaml

Add Windows and MacOS runner to CI self-test

---

src/reuse/init.py

Save users a trip to the search engine

Link to license list

---

AUTHORS.rst
CHANGELOG.md
pyproject.toml

Updated pyproject.toml file to add 0.1.34 in python-debian key
Fixes #807

Added 0.1.34 to pyproject.toml

---

.github/workflows/test.yaml
.github/workflows/third_party_lint.yaml

The goal of this change is to make sure that the poetry.lock file is compatible with the lowest supported Poetry version.

Pin Poetry version in CI

---

CHANGELOG.md
src/reuse/_annotate.py
tests/test_main_annotate.py

Re-introduce old behaviour under --skip-if-unrecognised 

---

AUTHORS.rst
CHANGELOG.md
src/reuse/comment.py

docs about bazel in regards to comments:
* https://bazel.build/run/bazelrc
* https://bazel.build/build/style-guide

add support for bazel files

---

AUTHORS.rst
CHANGELOG.md
src/reuse/_util.py
tests/test_main_annotate_merge.py

Fix crash when parsing year in `--merge-copyrights`

---

src/reuse/resources/exceptions.json
src/reuse/resources/licenses.json

update license list

---

CHANGELOG.md
src/reuse/project.py

Clearer instructions for --suppress-deprecation

---

CHANGELOG.md
poetry.lock
pyproject.toml
src/reuse/report.py
tests/test_main.py

Fix Created: datetime in spdx output

---

tests/test_report.py

Taken from #939, thanks to @smortex

Add test to ensure the date is properly formatted

---

CHANGELOG.md
src/reuse/comment.py

- <https://doc.rust-lang.org/cargo/appendix/glossary.html#lock-file>
- <https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html>

Add `Cargo.lock` support

---

CHANGELOG.md
src/reuse/comment.py

<https://clang.llvm.org/extra/clang-tidy/>

Add `.clang-tidy` support

---

src/reuse/vcs.py

Found in https://github.com/fsfe/reuse-tool/pull/899#discussion_r1581897029

Remove unnecessary code

---

.github/workflows/gettext.yaml
po/uk.po

Fixes #967 
Also fixes a merge conflict.

Fix weblate

---

CHANGELOG.md
poetry.lock
pyproject.toml

Removed upper limits for dependencies en passant.

Add change log entry for new dependencies

---

src/reuse/global_licensing.py
tests/test_global_licensing.py

Add some tests for asterisks

---

src/reuse/convert_dep5.py
tests/test_convert_dep5.py
tests/test_main.py

Make sure single asterisks become double asterisks in convert-dep5

---

CHANGELOG.md
src/reuse/comment.py

Add support for Apache HTTP server ".htaccess" file and npm ".npmrc" file
refs #985

Add .htaccess and .npmrc support

---

CONTRIBUTING.md

Add more steps post-release

---

src/reuse/_main.py
src/reuse/project.py
tests/conftest.py
tests/test_main.py

Do not print DEP5 deprecation warning during convert-dep5

---

docs/man/reuse-convert-dep5.rst
src/reuse/convert_dep5.py
tests/resources/dep5
tests/test_convert_dep5.py

Converting more fields, did some refactoring.

Improve `convert-dep5`

---

CHANGELOG.md
src/reuse/report.py

Fix invalid SPDX relationship

---

.github/pull_request_template.md
CHANGELOG.md
CONTRIBUTING.md
REUSE.toml
changelog.d/.protokolo.toml
changelog.d/added/.protokolo.toml
changelog.d/changed/.protokolo.toml
changelog.d/deprecated/.protokolo.toml
changelog.d/fixed/.protokolo.toml
changelog.d/removed/.protokolo.toml
changelog.d/security/.protokolo.toml
poetry.lock
pyproject.toml

Fixes #966. This will hopefully improve the quality of the change log and the quality of PRs.

Add Protokolo and PR template

---

AUTHORS.rst

Added all authors to AUTHORS.rst. I used `git shortlog` magic to get this list.
changed files.

Add all authors to AUTHORS.rst

---

.readthedocs.yaml
changelog.d/fixed/rtd.md

I am touching in the dark here… Compilation of documentation broke on RTD for no good reason. This is one way to address it.
changed files.

Make sure that readthedocs can compile the docs

---

.readthedocs.yaml

Followup of #1026
changed files.

Try to fix RTD issue

---

.readthedocs.yaml
changelog.d/fixed/rtd.md
poetry.lock
src/reuse/_util.py
src/reuse/download.py

Followup of #1027 and #1026
changed files.

Try to fix RTD

---

CHANGELOG.md
changelog.d/fixed/rtd.md
pyproject.toml
src/reuse/__init__.py

Release 4.0.1

---

changelog.d/fixed/merge.md
src/reuse/_util.py

In my haste, I introduced a bug in 4.0.1 when I fixed a linting error. This undoes that error.
changed files.

Repair a broken test

---

CHANGELOG.md
changelog.d/fixed/merge.md
pyproject.toml
src/reuse/__init__.py

Release 4.0.2

---

changelog.d/changed/remove-gitkeep.md
src/reuse/__init__.py

This is not in the spec.
changed files.

Remove .gitkeep from ignored list

---

changelog.d/fixed/min-version-attrs.md
poetry.lock
pyproject.toml

Older versions do not import.
Fixes #1039 
changed files.

Increase minimum version of attrs

---

CHANGELOG.md
changelog.d/fixed/min-version-attrs.md
poetry.lock
pyproject.toml
src/reuse/__init__.py

Release 4.0.3

---

.github/workflows/test.yaml
.github/workflows/third_party_lint.yaml
.readthedocs.yaml
README.md
changelog.d/removed/python-3.8.md
poetry.lock
pyproject.toml
src/reuse/__init__.py
src/reuse/_annotate.py
src/reuse/_licenses.py
src/reuse/_lint_file.py
src/reuse/_main.py
src/reuse/_util.py
src/reuse/comment.py
src/reuse/convert_dep5.py
src/reuse/covered_files.py
src/reuse/global_licensing.py
src/reuse/header.py
src/reuse/project.py
src/reuse/report.py
src/reuse/vcs.py

Remove Python 3.8 support

---

Makefile
src/reuse/cli/common.py

Generate .pot with all reuse Python files

---

CHANGELOG.md

Fix v5.0.0 date in change log

---

CHANGELOG.md
README.md
docs/conf.py
pyproject.toml
src/reuse/__init__.py

Release 5.0.2

---

CHANGELOG.md

Remove TODO in change log

---

.pre-commit-config.yaml
poetry.lock
src/reuse/global_licensing.py

This should repair the broken RTD build
changed files.

Regenerate poetry.lock

---

.github/workflows/close_inactive_issues.yaml

Perform more actions per run

---

.github/workflows/close_inactive_issues.yaml

- [x ] Added self to copyright blurb of touched files.
changed files.

Explicitly set permissions

---

changelog.d/added/supported-licenses-as-json.md
docs/man/reuse-supported-licenses.rst
src/reuse/cli/supported_licenses.py
tests/test_cli_supported_licenses.py

Closes #1186
Also, I fixed "SPDX-FileCopyrightTe**c**t" to "SPDX-FileCopyrightTe**x**t".
changed files.

feat(supported-licenses): Add `--json` flag

---

changelog.d/changed/cargo-lock-uncommentable.md
src/reuse/comment.py

chore: Revert `Cargo.lock` to uncommentable

---

src/reuse/cli/common.py
src/reuse/vcs.py
tests/conftest.py

Improve test performance

---

changelog.d/fixed/performance.md
src/reuse/_util.py
src/reuse/covered_files.py
src/reuse/extract.py
src/reuse/project.py
src/reuse/report.py
src/reuse/vcs.py
tests/conftest.py

I'm having a go at improving performance.
changed files.

More performance improvements

---

src/reuse/report.py
tests/conftest.py

Disable parallelisation during tests

---

.github/workflows/pijul.yaml
src/reuse/vcs.py

I introduced this bug in #1223, I think.
changed files.

Fix find_root for Pijul

---

REUSE.toml

Remove nonexistent files from REUSE.toml

---

AUTHORS.rst
changelog.d/added/added-pytyped.md
src/reuse/comment.py

Add support for py.typed files

---

changelog.d/added/invalid-expressions.md
changelog.d/changed/bad-licenses-per-file.md
changelog.d/changed/boolean-req.md
changelog.d/fixed/fix-parse-spdx-expression.md
docs/man/reuse-lint.rst
docs/man/reuse.rst
poetry.lock
pyproject.toml
src/reuse/__init__.py
src/reuse/cli/annotate.py
src/reuse/cli/common.py
src/reuse/copyright.py
src/reuse/extract.py
src/reuse/global_licensing.py
src/reuse/header.py
src/reuse/lint.py
src/reuse/project.py
src/reuse/report.py
tests/test_copyright.py
tests/test_extract.py
tests/test_global_licensing.py
tests/test_header.py
tests/test_lint.py
tests/test_project.py
tests/test_report.py

Fixes #4
Fixes #1228
changed files.

License parse fix

---

CHANGELOG.md
README.md
changelog.d/fixed/fix-format-lines.md
changelog.d/fixed/performance-regex.md
docs/conf.py
pyproject.toml
src/reuse/__init__.py

Release 6.1.2
